Screens:
    MainScreen:
    
<MainScreen>:
    name:'First'
    on_enter: root.hg()
    GridLayout:
        cols:1
        GridLayout:
            rows:2
            TextInput:
                #name:txt
                id:txt1
                text:'oko\nlol\npmo'
                background_color:(100,100,100,.8)
                font_size: 30
            Button:
                text:'submit'
                #on_press: print('say hello')
                #on_press: root.updat()
    
                